import FAQs from "@/components/about/faq";
import AboutIntro from "@/components/about/intro";
import Mission from "@/components/about/mission";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "About Us | LegalEase",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <>
      <AboutIntro />
      <Mission />
      <FAQs />
    </>
  );
}
