import ClientFeedback from "@/components/home/client-feedback";
import LawyerExpertise from "@/components/home/expertise";
import FeaturedLawyers from "@/components/home/featured-lawyers";
import Intro from "@/components/home/intro";
import LookingForLawyer from "@/components/home/looking";
import GotQuestions from "@/components/home/questions";
import WhatIsLegalEase from "@/components/home/what-is-legal-ease";
import Copyright from "@/components/layout/copyright";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home | LegalEase",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="min-h-screen">
      <Intro />
      <WhatIsLegalEase />
      <FeaturedLawyers />
      <GotQuestions />
      <LookingForLawyer />
      <LawyerExpertise />
      <ClientFeedback />
      <Copyright />
    </main>
  );
}
