import FindALawyer from "@/components/lawyers/find-lawyer";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Find a lawyer | LegalEase",
  description: "Generated by create next app",
};

export default function Page() {
  return <FindALawyer />;
}
